/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocolateriapup;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import javazoom.jl.player.Player;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.*;
import org.apache.pdfbox.pdmodel.font.PDTrueTypeFont;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import org.joda.time.DateTime;
import rst.pdfbox.layout.text.Alignment;
import rst.pdfbox.layout.elements.render.ColumnLayout;
import rst.pdfbox.layout.elements.*;
import rst.pdfbox.layout.elements.Document;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.mail.internet.MimeMultipart;
import javax.mail.internet.MimeBodyPart;

/**
 *
 * @author Isabella
 */
public class CosCumparaturi extends javax.swing.JFrame {

    /**
     * Creates new form CosCumparaturi
     */
    
    
    public static double total;
    
    
    public CosCumparaturi() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    public String filename;
    public Player player; 


    public CosCumparaturi(String filename) {
        this.filename = filename;
    }


    public void play() {
 try {   
            BufferedInputStream buffer = new BufferedInputStream(
    new FileInputStream(filename));
     player = new Player(buffer);
     player.play();
 }
 catch (Exception e) {

     System.out.println(e);
 }

    }
    
    
    private static String label_afisare;
    private static boolean gol =false;
    private static String produs;
    private static int nr_BD;
    
    private static String[] produse_cart = new String[20];
    private static int[] cantitate = new int[20];
    private static double[] preturi = new double[20];
    private static String tip ;
    private static String cautareProdus_tip(String denumire){
         try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
//            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
//            stmt.executeUpdate(strUpdate);
            PreparedStatement search = con.prepareStatement("Select * from `produse` where `denumire` like '"+denumire+"' ");
            ResultSet rst = search.executeQuery();
            int i=0;
            while(rst.next()){
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               tip = rst.getString("tip");
               i++;
            }
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
         return tip;
    }
//    private static String cautareProd_Afis(){
//        try{  
//            Class.forName("com.mysql.jdbc.Driver");  
//            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
//            Statement stmt=con.createStatement();
//            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
////            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
////            stmt.executeUpdate(strUpdate);
//            PreparedStatement search = con.prepareStatement("Select * from cart_item");
//            ResultSet rst = search.executeQuery();
//            
//            while(rst.next()){
////                 String to= rst.getString("Adresa Mail");
////                String parolaSQL = rst.getString("password");
//               
//            }
//            con.close();
//            
////            this.sendMail(to);
//        }catch(Exception e){ System.out.println(e);}
//    }
    private static void init_array(String[] cart_item){
        for(int i=0; i<cart_item.length; i++){
            cart_item[i]= "";
        }
    }
//    private static java.awt.Label prod_2;
//    private static java.awt.Label prod_3;
//    private static java.awt.Label prod_4;
    
    private static int nr_Produse;
    private static String[] cantitate_string = new String[20];
    private static String[] pret_string = new String[20];
    private static int nrProd_BD(){
        init_array(produse_cart);
        init_array(cantitate_string);
        init_array(pret_string);
        try{  
            
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
//            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
//            stmt.executeUpdate(strUpdate);
            PreparedStatement search = con.prepareStatement("Select * from `cart_item`");
            ResultSet rst = search.executeQuery();
            nr_BD=0;
            nr_Produse =0;
            int i=0;
            while(rst.next() ){
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               
               nr_BD++; 
//               for(i=0;i<20;i++){
                    cantitate[i] = rst.getInt("repetare");
                    produse_cart[i] = rst.getString("denumire");
                    preturi[i] = rst.getDouble("pret");
                    cantitate_string[i] = ""+cantitate[i]+"";
                    pret_string[i] = ""+preturi[i]+"";
//               }
               i++;
               nr_Produse++;
            }
            con.close();
            System.out.println("nr de prod : " +nr_BD);
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
        
        
        return nr_BD;
    }
    private static void afisare_produse(int n){
        for(int i=0;i<n;i++){
            System.out.println("prod. "+i+ " denumire "+ produse_cart[i]);
        }
    }
    private static String label_den, label_cant, label_pret; 
    private static String afis_denumire(){
        if(nrProd_BD() !=0){
            gol =false;
        }else if(nrProd_BD()==0){
            gol=true;
        }
        if(gol == true){
            label_den = " ";
        }else if(gol == false){
            label_den = "Denumire";
        }
        return label_den;
    }
    private static String afis_cantitate(){
        if(nrProd_BD() !=0){
            gol =false;
        }else if(nrProd_BD()==0){
            gol=true;
        }
        if(gol == true){
            label_cant = " ";
        }else if(gol == false){
            label_cant = "Cantitate";
        }
        return label_cant;
    }
//    private static String afis_tip(String denumire){
//        
//        if(nrProd_BD() !=0){
//            gol =false;
//            tip = cautareProdus_tip(denumire);
//        }else if(nrProd_BD()==0){
//            gol=true;
//        }
//        if(gol == true){
//            label_cant = " ";
//        }else if(gol == false){
//            label_cant = "Tip";
//        }
//        return label_cant;
//    }
    private static String afis_pret(){
        if(nrProd_BD() !=0){
            gol =false;
        }else if(nrProd_BD()==0){
            gol=true;
        }
        if(gol == true){
            label_pret = " ";
        }else if(gol == false){
            label_pret = "Pret";
        }
        return label_pret;
    }
    
    private static String label_total;
    private static String afis_total(){
        if(nrProd_BD() !=0){
            gol =false;
        }else if(nrProd_BD()==0){
            gol=true;
        }
        if(gol == true){
            label_total = " ";
        }else if(gol == false){
            label_total = "Total:";
        }
        return label_total;
    }
    
    private static double totalul=0;
    private static double calculareTotal(){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
//            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
//            stmt.executeUpdate(strUpdate);
            PreparedStatement search = con.prepareStatement("Select * from `cart_item` ");
            ResultSet rst = search.executeQuery();
            
            while(rst.next()){
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               double buffer = rst.getDouble("pret");
               totalul = totalul+ buffer;
            }
            con.close();
            System.out.println("total: "+totalul);
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
        return totalul;
    }
    
    private static String afisare_total_nr;
    private static String afis_total_nr(){
        totalul=0;
        if(nrProd_BD() !=0){
            gol =false;
        }else if(nrProd_BD()==0){
            gol=true;
        }
        if(gol == true){
            afisare_total_nr = " ";
        }else if(gol == false){
            afisare_total_nr= ""+calculareTotal()+"";
        }
        return afisare_total_nr;
    }
    
    private static String afis_titlu(){
        if(nrProd_BD() !=0){
            gol =false;
        }else if(nrProd_BD()==0){
            gol=true;
        }
        if(gol == true){
            label_afisare = "Cosul dvs. este gol.";
        }else if(gol == false){
            label_afisare = "Produsele dvs din cos: ";
        }
        return label_afisare;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buton_cos_cumparaturi = new java.awt.Button();
        buton_prajituri = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        buton_ornamente = new java.awt.Button();
        buton_torturi = new java.awt.Button();
        buton_praj_japoneze = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label_cos_gol = new java.awt.Label();
        prod_0 = new java.awt.Label();
        prod_1 = new java.awt.Label();
        prod_2 = new java.awt.Label();
        prod_3 = new java.awt.Label();
        prod_4 = new java.awt.Label();
        prod_5 = new java.awt.Label();
        prod_6 = new java.awt.Label();
        prod_7 = new java.awt.Label();
        prod_8 = new java.awt.Label();
        prod_9 = new java.awt.Label();
        prod_10 = new java.awt.Label();
        denumire_label = new javax.swing.JLabel();
        cantitate_label = new javax.swing.JLabel();
        pret_label = new javax.swing.JLabel();
        cant_prod0 = new java.awt.Label();
        cant_prod1 = new java.awt.Label();
        cant_prod2 = new java.awt.Label();
        cant_prod3 = new java.awt.Label();
        cant_prod4 = new java.awt.Label();
        cant_prod5 = new java.awt.Label();
        cant_prod6 = new java.awt.Label();
        cant_prod7 = new java.awt.Label();
        cant_prod8 = new java.awt.Label();
        cant_prod9 = new java.awt.Label();
        cant_prod10 = new java.awt.Label();
        pret_prod0 = new java.awt.Label();
        pret_prod1 = new java.awt.Label();
        pret_prod2 = new java.awt.Label();
        pret_prod3 = new java.awt.Label();
        pret_prod4 = new java.awt.Label();
        pret_prod5 = new java.awt.Label();
        pret_prod6 = new java.awt.Label();
        pret_prod7 = new java.awt.Label();
        pret_prod8 = new java.awt.Label();
        pret_prod9 = new java.awt.Label();
        pret_prod10 = new java.awt.Label();
        label_tottal = new java.awt.Label();
        label_total_nr = new java.awt.Label();
        buton_generare_fact = new java.awt.Button();
        buton_generare_fact1 = new java.awt.Button();
        buton_comanda = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buton_cos_cumparaturi.setBackground(new java.awt.Color(0, 204, 153));
        buton_cos_cumparaturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_cos_cumparaturi.setLabel("Cos de cumparaturi");

        buton_prajituri.setBackground(new java.awt.Color(255, 153, 153));
        buton_prajituri.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_prajituri.setLabel("Prajituri");
        buton_prajituri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_prajituriActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/logo.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));

        buton_ornamente.setBackground(new java.awt.Color(255, 153, 153));
        buton_ornamente.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_ornamente.setLabel("Ornamente");
        buton_ornamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ornamenteActionPerformed(evt);
            }
        });

        buton_torturi.setBackground(new java.awt.Color(255, 153, 153));
        buton_torturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_torturi.setLabel("Torturi");
        buton_torturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_torturiActionPerformed(evt);
            }
        });

        buton_praj_japoneze.setBackground(new java.awt.Color(255, 153, 153));
        buton_praj_japoneze.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_praj_japoneze.setLabel("Prajituri japoneze");
        buton_praj_japoneze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_praj_japonezeActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Times New Roman", 1, 35)); // NOI18N
        label1.setText("Cosul dvs. de cumparaturi");

        label_afisare = afis_titlu();
        label_cos_gol.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        label_cos_gol.setText(label_afisare);

        prod_0.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_0.setText(produse_cart[0]);

        prod_1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_1.setText(produse_cart[1]);

        prod_2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_2.setText(produse_cart[2]);

        prod_3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_3.setText(produse_cart[3]);

        prod_4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_4.setText(produse_cart[4]);

        prod_5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_5.setText(produse_cart[5]);

        prod_6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_6.setText(produse_cart[6]);

        prod_7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_7.setText(produse_cart[7]);

        prod_8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_8.setText(produse_cart[8]);

        prod_9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_9.setText(produse_cart[9]);

        prod_10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        prod_10.setText(produse_cart[10]);

        denumire_label.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        denumire_label.setText(afis_denumire());

        cantitate_label.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cantitate_label.setText(afis_cantitate());

        pret_label.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_label.setText(afis_pret());

        cant_prod0.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod0.setText(cantitate_string[0]);

        cant_prod1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod1.setText(cantitate_string[1]);

        cant_prod2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod2.setText(cantitate_string[2]);

        cant_prod3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod3.setText(cantitate_string[3]);

        cant_prod4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod4.setText(cantitate_string[4]);

        cant_prod5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod5.setText(cantitate_string[5]);

        cant_prod6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod6.setText(cantitate_string[6]);

        cant_prod7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod7.setText(cantitate_string[7]);

        cant_prod8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod8.setText(cantitate_string[8]);

        cant_prod9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod9.setText(cantitate_string[9]);

        cant_prod10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        cant_prod10.setText(cantitate_string[10]);

        pret_prod0.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod0.setText(pret_string[0]);

        pret_prod1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod1.setText(pret_string[1]);

        pret_prod2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod2.setText(pret_string[2]);

        pret_prod3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod3.setText(pret_string[3]);

        pret_prod4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod4.setText(pret_string[4]);

        pret_prod5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod5.setText(pret_string[5]);

        pret_prod6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod6.setText(pret_string[6]);

        pret_prod7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod7.setText(pret_string[7]);

        pret_prod8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod8.setText(pret_string[8]);

        pret_prod9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod9.setText(pret_string[9]);

        pret_prod10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        pret_prod10.setText(pret_string[10]);

        label_tottal.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        label_tottal.setText(afis_total());

        label_total_nr.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        label_total_nr.setText(afis_total_nr());

        buton_generare_fact.setBackground(new java.awt.Color(255, 102, 102));
        buton_generare_fact.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        buton_generare_fact.setLabel("Genereaza factura");
        buton_generare_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_generare_factActionPerformed(evt);
            }
        });

        buton_generare_fact1.setBackground(new java.awt.Color(255, 102, 102));
        buton_generare_fact1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        buton_generare_fact1.setLabel("Trimite Factura");
        buton_generare_fact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_generare_fact1ActionPerformed(evt);
            }
        });

        buton_comanda.setBackground(new java.awt.Color(0, 204, 204));
        buton_comanda.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        buton_comanda.setLabel("Comanda");
        buton_comanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_comandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label_cos_gol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(prod_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(prod_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(denumire_label)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(prod_8, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                                            .addComponent(prod_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(prod_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGap(9, 9, 9)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(cant_prod3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cant_prod2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cant_prod0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cant_prod1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cant_prod4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cant_prod5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cant_prod6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(cant_prod7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addGap(1, 1, 1)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cant_prod8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cant_prod9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cant_prod10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(101, 101, 101))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(108, 108, 108)
                                                .addComponent(cantitate_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(buton_generare_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(buton_generare_fact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_tottal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pret_prod0, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pret_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pret_prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pret_prod3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pret_prod4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pret_prod5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pret_prod6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(pret_prod10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pret_prod9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(label_total_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pret_prod7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pret_prod8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(pret_label)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(712, 712, 712)
                        .addComponent(buton_comanda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(label_cos_gol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(denumire_label)
                    .addComponent(cantitate_label)
                    .addComponent(pret_label))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prod_0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prod_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cant_prod0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cant_prod10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pret_prod0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pret_prod10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_total_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_tottal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_generare_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_generare_fact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_comanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_prajituriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_prajituriActionPerformed
        // TODO add your handling code here:
        
        nrProd_BD();
        afisare_produse(nr_Produse);
        PrajituriForm prajForm = new PrajituriForm();
        prajForm.show();
        dispose();
    }//GEN-LAST:event_buton_prajituriActionPerformed

    private void buton_ornamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ornamenteActionPerformed
        // TODO add your handling code here:
        OrnamenteForm orn = new OrnamenteForm();
        orn.show();
        dispose();
    }//GEN-LAST:event_buton_ornamenteActionPerformed

    private void buton_torturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_torturiActionPerformed
        // TODO add your handling code here:
        TorturiForm tort = new TorturiForm();
        tort.show();
        dispose();
    }//GEN-LAST:event_buton_torturiActionPerformed

    private void buton_praj_japonezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_praj_japonezeActionPerformed
        // TODO add your handling code here:
        PrajituriJaponezeForm japan = new PrajituriJaponezeForm();
        japan.show();
        dispose();
    }//GEN-LAST:event_buton_praj_japonezeActionPerformed
    FacturareInterface fact = new FacturareInterface();
    private void buton_generare_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_generare_factActionPerformed
        // TODO add your handling code here:
       
        try{
            fact.facturareInPDF_v2();
        }catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_buton_generare_factActionPerformed

    private void buton_generare_fact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_generare_fact1ActionPerformed
        // TODO add your handling code here:
        Inregistrare inreg = new Inregistrare();
        
        
        fact.trimitereFactEmail(inreg.adresa);
       
        
    }//GEN-LAST:event_buton_generare_fact1ActionPerformed
    private int n;
    private String nume_client,client_id, status= "livrare", telefon, email, adresaLiv, oras, tara;
    private int tax=9, ship_tax=10, discount;
    private double subtotal;
            //9%taxa //5% taxa transport

    private void buton_comandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_comandaActionPerformed
        // TODO add your handling code here:
        //buton_comanda
        FacturareInterface.getDateClient(Pag1.username);
        n=0;
        subtotal = totalul;
         try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //String strSelect = "SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"' " ;
           PreparedStatement search = con.prepareStatement("Select * from cart_item");
            ResultSet rst = search.executeQuery();
            
            while(rst.next()){
                n++;
                discount = rst.getInt("discount");
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               //produs_id = rst.getInt("id");
               //discount = rst.getInt("discount");
               //pret = rst.getDouble("pret");
            }
            Random rnd = new Random();
            int token = rnd.nextInt(999999);
            totalul=totalul- (totalul * (discount/100)) + (totalul * ((double)tax/100)) + ship_tax;
            System.out.println("total = "+ totalul);
            String strUpdate = "INSERT INTO `comenzi` (`id`, `user_id`, `token`, `status`, `subtotal`, `tax`, `shipping_tax`, `total`, `discount`, `nume_user`, `telefon`, `email`, `adresaLivrare`, `judet`, `tara`) " +
                    "VALUES (NULL, '"+FacturareInterface.id_user+"' ,'"+token+"' , '"+status+"', '"+subtotal+"', '"+tax+"', '"+ship_tax+"', '"+totalul+"', '"+discount+"', '"+FacturareInterface.nume+"', '"+FacturareInterface.telefon+"'"+
                    ", '"+FacturareInterface.email+"', '"+FacturareInterface.adresaStr+"', '"+FacturareInterface.judet+"', '"+FacturareInterface.tara+"')";
            stmt.executeUpdate(strUpdate);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }//GEN-LAST:event_buton_comandaActionPerformed

    LocalDate today = LocalDate.now( );
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
    DateTimeFormatter df = DateTimeFormatter.ofPattern( "dd.MM.yyyy" );
    
    LocalDate dataScadenta = today.plusDays(15);
    
    
    
    public void trimitereFactEmail(String t){
        // Recipient's email ID needs to be mentioned.
      String to = t;//change accordingly

      // Sender's email ID needs to be mentioned
      String from = "chocolateriapup@gmail.com";//change accordingly
      final String username = "chocolateriapup@gmail.com";//change accordingly
      final String passwordg = "abofajsvoxpoxape";//change accordingly

      // Assuming you are sending email through relay.jangosmtp.net
      String host = "smtp.gmail.com";

      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "587");

      // Get the Session object.
      Session session = Session.getInstance(props,
      new javax.mail.Authenticator() {
         protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(username, passwordg);
         }
      });

      try {
          
         // Create a default MimeMessage object.
         Message message = new MimeMessage(session);

         // Set From: header field of the header.
         message.setFrom(new InternetAddress(from));

         // Set To: header field of the header.
         message.setRecipients(Message.RecipientType.TO,
         InternetAddress.parse(to));
         // Set Subject: header field
         message.setSubject("Factura din data de "+today.format(df));
           MimeBodyPart attachmentPart = new MimeBodyPart();
           MimeMultipart multipart = new MimeMultipart();
           MimeBodyPart textPart = new MimeBodyPart();
           
           try {

                File f =new File("C:\\Users\\User\\Desktop\\ChocolateriaPup\\src\\resurse\\FacturaImag_nr100002.pdf");
                
                attachmentPart.attachFile(f);
                textPart.setText("Buna ziua, \n\nAtasat se afla factura dvs. din data de "+today.format(df)+" cu numarul 100002\n \n \n Echipa Chocolateria Pup.");
                 multipart.addBodyPart(textPart);
                multipart.addBodyPart(attachmentPart);

            } catch (IOException e) {

                e.printStackTrace();

            }

//         // Set Subject: header field
//         message.setSubject("Factura din data de "+today.format(df));
//          
//         // Now set the actual message
//         message.setText("Buna ziua, \n\nAtasat se afla factura dvs. din data de "+today.format(df)+"cu numarul "+facturaNo+ "\n \n \n Echipa Chocolateria Pup.");
        message.setContent(multipart);
         // Send message
         Transport.send(message);

         System.out.println("Sent message successfully....");

      } catch (MessagingException e) {
            throw new RuntimeException(e);
      }
    }
    
        
    
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CosCumparaturi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CosCumparaturi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CosCumparaturi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CosCumparaturi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CosCumparaturi().setVisible(true);
            }
        });
        
        CosCumparaturi mp3 = new CosCumparaturi("C:\\Users\\User\\Desktop\\ChocolateriaPup\\src\\resurse\\bosanka.mp3");
        mp3.play();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buton_comanda;
    private java.awt.Button buton_cos_cumparaturi;
    private java.awt.Button buton_generare_fact;
    private java.awt.Button buton_generare_fact1;
    private java.awt.Button buton_ornamente;
    private java.awt.Button buton_praj_japoneze;
    private java.awt.Button buton_prajituri;
    private java.awt.Button buton_torturi;
    private static java.awt.Label cant_prod0;
    private static java.awt.Label cant_prod1;
    private static java.awt.Label cant_prod10;
    private static java.awt.Label cant_prod2;
    private static java.awt.Label cant_prod3;
    private static java.awt.Label cant_prod4;
    private static java.awt.Label cant_prod5;
    private static java.awt.Label cant_prod6;
    private static java.awt.Label cant_prod7;
    private static java.awt.Label cant_prod8;
    private static java.awt.Label cant_prod9;
    private javax.swing.JLabel cantitate_label;
    private javax.swing.JLabel denumire_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private static java.awt.Label label_cos_gol;
    private java.awt.Label label_total_nr;
    private java.awt.Label label_tottal;
    private javax.swing.JLabel pret_label;
    private static java.awt.Label pret_prod0;
    private static java.awt.Label pret_prod1;
    private static java.awt.Label pret_prod10;
    private static java.awt.Label pret_prod2;
    private static java.awt.Label pret_prod3;
    private static java.awt.Label pret_prod4;
    private static java.awt.Label pret_prod5;
    private static java.awt.Label pret_prod6;
    private static java.awt.Label pret_prod7;
    private static java.awt.Label pret_prod8;
    private static java.awt.Label pret_prod9;
    private static java.awt.Label prod_0;
    private static java.awt.Label prod_1;
    private static java.awt.Label prod_10;
    private static java.awt.Label prod_2;
    private static java.awt.Label prod_3;
    private static java.awt.Label prod_4;
    private static java.awt.Label prod_5;
    private static java.awt.Label prod_6;
    private static java.awt.Label prod_7;
    private static java.awt.Label prod_8;
    private static java.awt.Label prod_9;
    // End of variables declaration//GEN-END:variables
}
