/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocolateriapup;

import java.util.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import org.springframework.security.crypto.bcrypt.BCrypt;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.awt.Desktop;  
import java.io.*; 
/**
 *
 * @author Isabella
 */
public class Inregistrare extends javax.swing.JFrame {

    /**
     * Creates new form Inregistrare
     */
    public Inregistrare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        username_field = new java.awt.TextField();
        label3 = new java.awt.Label();
        parola_field = new javax.swing.JPasswordField();
        label4 = new java.awt.Label();
        email_field = new java.awt.TextField();
        nume_client_field = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        button1 = new java.awt.Button();
        label5 = new java.awt.Label();
        tip_client = new javax.swing.JComboBox<>();
        label6 = new java.awt.Label();
        tara_label = new java.awt.Label();
        tara_field = new java.awt.TextField();
        judet_field = new java.awt.TextField();
        tara_label1 = new java.awt.Label();
        tara_label2 = new java.awt.Label();
        adresa_field = new java.awt.TextField();
        tara_label3 = new java.awt.Label();
        telefon_field = new java.awt.TextField();
        label7 = new java.awt.Label();
        isAnAdmin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Times New Roman", 3, 25)); // NOI18N
        label1.setText("Hai sa te pregatim.");

        label2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label2.setText("Username:");

        username_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        label3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label3.setText("Parola:");

        parola_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        label4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label4.setText("Adresa mail:");

        email_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        nume_client_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jButton1.setText("Inregistreaza-ma!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(255, 51, 51));
        button1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        button1.setLabel("Inapoi");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label5.setText("Nume:");

        tip_client.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tip_client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persoana fizica", "Persoana juridica" }));

        label6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label6.setText("Tip client:");

        tara_label.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tara_label.setText("Tara:");

        tara_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        judet_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        tara_label1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tara_label1.setText("Judet:");

        tara_label2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tara_label2.setText("Adresa:");

        adresa_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        tara_label3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        tara_label3.setText("Telefon:");

        telefon_field.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        label7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label7.setText("Tip:");

        isAnAdmin.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        isAnAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Client", "Admin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tara_label, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nume_client_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(parola_field)
                                    .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(username_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tip_client, 0, 191, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tara_label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(tara_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(214, 214, 214)
                                    .addComponent(jButton1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(243, 243, 243)
                                    .addComponent(tara_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tara_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(judet_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adresa_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefon_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isAnAdmin, 0, 205, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(username_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tara_label, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(tara_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(parola_field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(judet_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tara_label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tara_label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adresa_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tara_label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nume_client_field, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(telefon_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tip_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(isAnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String password,autentifCode, status;
    public static String hashedPassword;
    public static String adresa="isabela_hasnas@yahoo.com", username, porecla;
    public static String generatedCode;
    private String generateCode(){
        Random rnd = new Random();
        int number = rnd.nextInt(999999);
        autentifCode = String.format("%06d", number);
        return autentifCode;
    }
    private String hashPassword(String pass){
//        System.out.println(BCrypt.gensalt());
        return BCrypt.hashpw(pass, "$2a$10$bd2CCvtz9ecKmyiUN2NuWu");
        
    }
//    private boolean Verify_Password(String password, String hashedPassword){
//        return BCrypt.checkpw(password, hashedPassword);
//    }
    private void sendMail(String t){
        // Recipient's email ID needs to be mentioned.
      String to = t;//change accordingly

      // Sender's email ID needs to be mentioned
      String from = "chocolateriapup@gmail.com";//change accordingly
      final String username = "chocolateriapup@gmail.com";//change accordingly
      final String passwordg = "abofajsvoxpoxape";//change accordingly

      // Assuming you are sending email through relay.jangosmtp.net
      String host = "smtp.gmail.com";

      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "587");

      // Get the Session object.
      Session session = Session.getInstance(props,
      new javax.mail.Authenticator() {
         protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(username, passwordg);
         }
      });

      try {
         // Create a default MimeMessage object.
         Message message = new MimeMessage(session);

         // Set From: header field of the header.
         message.setFrom(new InternetAddress(from));

         // Set To: header field of the header.
         message.setRecipients(Message.RecipientType.TO,
         InternetAddress.parse(to));

         // Set Subject: header field
         message.setSubject("Confirm your account");
          generatedCode = this.generateCode();
         // Now set the actual message
         message.setText("Buna ziua "+this.porecla+", \n \n Noi suntem Chocolateria Pup si va multumim pentru contul facut in cadrul aplicatiei noastre.\n"
            + " Mai jos se afla codul dvs. de autentificare: "+ "\n" + autentifCode + "\n\n Va rugam sa va conectati in aplicatie folosind acest cont. "
                    + "\n \n \n Echipa Chocolateria Pup.");

         // Send message
         Transport.send(message);

         System.out.println("Sent message successfully....");

      } catch (MessagingException e) {
            throw new RuntimeException(e);
      }
    }
    public String returnAdresa(){
        return email_field.getText();
    }
    public String getAdresa(){
        adresa = email_field.getText();
        return adresa;
    }
//    public String
    
    //METODA VERIF. NR DE TEL PT TOATE TARILE.
    private static boolean valid_number(String tel){
        Pattern tel_pattern = Pattern.compile("^(\\+\\d{1,3}( )?)?((\\(\\d{1,3}\\))|\\d{1,3})[- .]?\\d{3,4}[- .]?\\d{4}$");
        Matcher m =tel_pattern.matcher(tel);
        return(m.matches());
    }
    
    
    
    private String tipClient, tara_client, judet_client, adresa_client, telefon, isAdmin, adresaIp, dataInreg, host;
    private boolean tara_confirmare;
     LocalDate today = LocalDate.now( );
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
    DateTimeFormatter df = DateTimeFormatter.ofPattern( "dd.MM.yyyy" );
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pag1.loginmode = "Register";
        username = username_field.getText();
        password = parola_field.getText();
        adresa = email_field.getText();
        porecla = nume_client_field.getText();
        tipClient = tip_client.getSelectedItem().toString();
        
        tara_client = tara_field.getText();
        judet_client = judet_field.getText();
        adresa_client = adresa_field.getText();
        telefon = telefon_field.getText();
        
//        if(valid_number(telefon)== false){
//            JOptionPane.showMessageDialog(null,"Numarul de telefon introdus nu este valid.");
//        }
        isAdmin = isAnAdmin.getSelectedItem().toString();
        
//        System.out.println("tip : " +tipClient);
//        this.sendMail();
//        password = this.hashPassword(password);
        hashedPassword= this.hashPassword(password);
//        System.out.println("pass: "+password);
        if(username.isEmpty()|| password.isEmpty() || adresa.isEmpty() || porecla.isEmpty() || tara_client.isEmpty() || judet_client.isEmpty() || adresa_client.isEmpty() || telefon.isEmpty()){
            JOptionPane.showMessageDialog(null, "Campurile nu trebuie sa fie goale. Va rugam sa introduceti datele dvs corecte. ");
        }else{
            if(username.length()<5 ){
                JOptionPane.showMessageDialog(null,"Username-ul trebuie sa contina cel putin 5 caractere.");
            }
            if(username.length()>5 && (password.length()<6 || !(password.matches(".*[0-9].*"))) ){
                JOptionPane.showMessageDialog(null,"Parola-ul trebuie sa contina cel putin 6 caractere si un numar.");
            }
            
            if(valid_number(telefon)== false){
                JOptionPane.showMessageDialog(null,"Numarul de telefon introdus nu este valid. Reincercati cu prefixul tarii dvs. (ex. +40)");
            }else{
                Pattern pattern = Pattern.compile("[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}");
                Matcher mat = pattern.matcher(adresa); //VERIFICA DACA ADRESA ARE STRUCTURA CEVA..CEVA@CEVA.CEVA
                
                try{  
                    //constructor of file class having file as argument  
                    File file = new File("C:\\Users\\User\\Desktop\\ChocolateriaPup\\src\\resurse\\tari.txt"); 
                    BufferedReader br=new BufferedReader(new FileReader(file));  
//                    int r=0;  
                    String line;
                     tara_confirmare=false;
                    while((line = br.readLine()) !=null){
                        if(line.contains(tara_client)){
                            tara_confirmare =true;
                        }
                    } 
                }catch(Exception e){  
                    e.printStackTrace();  
                }  
                
                if(tara_confirmare ==false){
                    JOptionPane.showMessageDialog(null, "Tara introdusa nu este valida. Reincercati. ");
                }else{
                    if(mat.matches()){
                        this.sendMail(adresa);
                        status = "Inactive";
                        dataInreg = today.format(df).toString();

                        try{
                            InetAddress ip = InetAddress.getLocalHost();

                            adresaIp = ip.getHostAddress().toString();
                            host = ip.toString();

        //                    System.out.println("IP of my system is := "+IP.getHostAddress());
                        }catch(UnknownHostException ex){
                            Logger.getLogger(Inregistrare.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        try{  
                            Class.forName("com.mysql.jdbc.Driver");  
                            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
                            Statement stmt=con.createStatement();
                //            String strSelect = "SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"' " ;
                            //DE UPDATAT
                            String sqlUpdate = "INSERT INTO `conturi` (`client_id`, `username`, `password`, `TipClient`, `Nume`, `Adresa Mail`, `NrTelefon`, "
                                    + "`adresa_livrare`, `judet`, `tara`, `Active/Inactive`, `ActivatingCode`, `Admin`, `host`, `adresaIP`,"
                                    + " `InregistrareData`, `LastLogin`) VALUES (NULL,'"+username+"', '"+hashedPassword+"', '"+tipClient+"',"
                                    + " '"+porecla+"', '"+adresa+"', '"+telefon+"' , '"+adresa_client+"', '"+judet_client+"' ,"
                                    + " '"+tara_client+"' ,'"+status+"','"+generatedCode+"', '"+isAdmin+"', '"+host+"' ,'"+adresaIp+"','"+dataInreg+"', '"+dataInreg+"' )";

                            stmt.executeUpdate(sqlUpdate);


                            con.close();
                        }catch(Exception e){ System.out.println(e);}
            //            Pag1 pg1 = new Pag1();
            //            pg1.show();
            //            dispose();
                        Confirmare_email_v2 conf = new Confirmare_email_v2();
                        conf.show();
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(null, "Adresa de email introdusa nu este buna. Reincercati. ");
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        //BUTON ROSU BACK
        Pag1 pg1 = new Pag1();
        pg1.show();
        dispose();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inregistrare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inregistrare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField adresa_field;
    private java.awt.Button button1;
    private java.awt.TextField email_field;
    private javax.swing.JComboBox<String> isAnAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField judet_field;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField nume_client_field;
    private javax.swing.JPasswordField parola_field;
    private java.awt.TextField tara_field;
    private java.awt.Label tara_label;
    private java.awt.Label tara_label1;
    private java.awt.Label tara_label2;
    private java.awt.Label tara_label3;
    private java.awt.TextField telefon_field;
    private javax.swing.JComboBox<String> tip_client;
    private java.awt.TextField username_field;
    // End of variables declaration//GEN-END:variables
}
