/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocolateriapup;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javazoom.jl.player.Player;

/**
 *
 * @author Isabella
 */
public class OrnamenteForm extends javax.swing.JFrame {

    /**
     * Creates new form OrnamenteForm
     */
    public OrnamenteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buton_ornamente = new java.awt.Button();
        buton_torturi = new java.awt.Button();
        buton_cos_cumparaturi = new java.awt.Button();
        buton_prajituri = new java.awt.Button();
        buton_praj_japoneze = new java.awt.Button();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        buton_decor_ursuleti = new java.awt.Button();
        label3 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        buton_pasta_modelat = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        buton_perle_ciocolata_alba = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        buton_decor_floricele = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        buton_trandafiri_albi_perlati = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        buton_trandafiri_modelati = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        buton_figurina_nunta = new java.awt.Button();
        jLabel9 = new javax.swing.JLabel();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        buton_phoenix = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        buton_cuplu_fazani = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/logo.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));

        buton_ornamente.setBackground(new java.awt.Color(255, 153, 153));
        buton_ornamente.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_ornamente.setLabel("Ornamente");
        buton_ornamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ornamenteActionPerformed(evt);
            }
        });

        buton_torturi.setBackground(new java.awt.Color(255, 153, 153));
        buton_torturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_torturi.setLabel("Torturi");
        buton_torturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_torturiActionPerformed(evt);
            }
        });

        buton_cos_cumparaturi.setBackground(new java.awt.Color(0, 204, 153));
        buton_cos_cumparaturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_cos_cumparaturi.setLabel("Cos de cumparaturi");
        buton_cos_cumparaturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_cos_cumparaturiActionPerformed(evt);
            }
        });

        buton_prajituri.setBackground(new java.awt.Color(255, 153, 153));
        buton_prajituri.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_prajituri.setLabel("Prajituri");
        buton_prajituri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_prajituriActionPerformed(evt);
            }
        });

        buton_praj_japoneze.setBackground(new java.awt.Color(255, 153, 153));
        buton_praj_japoneze.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_praj_japoneze.setLabel("Prajituri japoneze");
        buton_praj_japoneze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_praj_japonezeActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/decor-zahar-figurine-panda-1-5-4-cm-4-modele-8-buc.png"))); // NOI18N

        label1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label1.setText("Decor Ursuleti 8 buc/pachet");

        label2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("18 RON / buc");

        buton_decor_ursuleti.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_decor_ursuleti.setLabel("Adauga");
        buton_decor_ursuleti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_decor_ursuletiActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label3.setText("Pasta de modelat 1kg");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/pasta-de-modelat-alba-1kg.png"))); // NOI18N

        label4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label4.setName(""); // NOI18N
        label4.setText("29,50 RON / buc");

        buton_pasta_modelat.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_pasta_modelat.setLabel("Adauga");
        buton_pasta_modelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_pasta_modelatActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/perle_de_ciocolata_alba.jpg"))); // NOI18N

        label5.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label5.setText("Perle de Ciocolata Alba 1,2 kg");

        label6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("72,85 RON / buc");

        buton_perle_ciocolata_alba.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_perle_ciocolata_alba.setLabel("Adauga");
        buton_perle_ciocolata_alba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_perle_ciocolata_albaActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/decor-floricele-12buc.png"))); // NOI18N

        label7.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label7.setText("Decor Flori 12 buc / pachet");

        label8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label8.setName(""); // NOI18N
        label8.setText("39,99 RON / buc");

        buton_decor_floricele.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_decor_floricele.setLabel("Adauga");
        buton_decor_floricele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_decor_floriceleActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/decor-zahar-trandafiri-alb-perlat-5cm-24-buc.jpg"))); // NOI18N

        label9.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label9.setText("Decor Trandafir Alb Perlat, 24 buc");

        label10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label10.setName(""); // NOI18N
        label10.setText("153,71 RON / buc");

        buton_trandafiri_albi_perlati.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_trandafiri_albi_perlati.setLabel("Adauga");
        buton_trandafiri_albi_perlati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_trandafiri_albi_perlatiActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/trandafiri_modelati.jpg"))); // NOI18N

        label11.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label11.setText("Trandafiri Modelati 12 buc/pachet");

        label12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label12.setName(""); // NOI18N
        label12.setText("18,50 RON / buc");

        buton_trandafiri_modelati.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_trandafiri_modelati.setLabel("Adauga");
        buton_trandafiri_modelati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_trandafiri_modelatiActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/figurina_nunta_1.jpg"))); // NOI18N

        label13.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label13.setText("Figurina Nunta");

        label14.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label14.setName(""); // NOI18N
        label14.setText("55 RON / buc");

        buton_figurina_nunta.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_figurina_nunta.setLabel("Adauga");
        buton_figurina_nunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_figurina_nuntaActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/figurina_phoenix.png"))); // NOI18N

        label15.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label15.setText("Figurina Phoenix Handmade");

        label16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label16.setName(""); // NOI18N
        label16.setText("257 RON / buc");

        buton_phoenix.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_phoenix.setLabel("Adauga");
        buton_phoenix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_phoenixActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/cuplu_fazani.jpg"))); // NOI18N

        label17.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label17.setText("Figurina Cuplu Fazani Handmade");

        label18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label18.setName(""); // NOI18N
        label18.setText("257 RON / buc");

        buton_cuplu_fazani.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_cuplu_fazani.setLabel("Adauga");
        buton_cuplu_fazani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_cuplu_fazaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buton_decor_ursuleti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buton_pasta_modelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(buton_trandafiri_albi_perlati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_trandafiri_modelati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buton_perle_ciocolata_alba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(buton_decor_floricele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(212, 212, 212))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(buton_phoenix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(buton_figurina_nunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)))
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(buton_cuplu_fazani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_decor_ursuleti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_pasta_modelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buton_perle_ciocolata_alba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_decor_floricele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_trandafiri_albi_perlati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_trandafiri_modelati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_figurina_nunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_phoenix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_cuplu_fazani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public String filename;
    public Player player; 


    public OrnamenteForm(String filename) {
 this.filename = filename;
    }


    public void play() {
 try {   
            BufferedInputStream buffer = new BufferedInputStream(
    new FileInputStream(filename));
     player = new Player(buffer);
     player.play();
 }
 catch (Exception e) {

     System.out.println(e);
 }
    }
    
     private int produs_id, discount, repetare=0;
    private double pret;
    
    private void cautareProd(String denumire, String tip){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
//            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
//            stmt.executeUpdate(strUpdate);
            PreparedStatement search = con.prepareStatement("Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"' ");
            ResultSet rst = search.executeQuery();
            
            while(rst.next()){
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               produs_id = rst.getInt("id");
               discount = rst.getInt("discount");
               pret = rst.getDouble("pret");
            }
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }
    private void adaugareItem(String denumireProd, int repetari){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            String strUpdate = "INSERT INTO `cart_item` (`id`, `produs_id`, `denumire` ,`pret`, `discount`, `repetare`) "
                    + "VALUES (NULL, '"+produs_id+"', '"+denumireProd+"' ,'"+pret+"', '"+discount+"', '"+repetari+"');";
            stmt.executeUpdate(strUpdate);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }
    private double pretUpdate;
    private void updateItem(String denumire, int repetari){
        try{  
            
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            String strUpdate = "UPDATE `cart_item` SET `repetare` = '"+repetari+"' WHERE `cart_item`.`denumire` LIKE '"+denumire+"' ";
            stmt.executeUpdate(strUpdate);
            String strUpdatePret = "UPDATE `cart_item` set `pret` = '"+pret+"'*'"+repetari+"' WHERE `cart_item`.`denumire` LIKE '"+denumire+"' ";
            stmt.executeUpdate(strUpdatePret);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
        
    }
    
    
    private void buton_prajituriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_prajituriActionPerformed
        // TODO add your handling code here:
        PrajituriForm prajForm = new PrajituriForm();
        prajForm.show();
        dispose();
    }//GEN-LAST:event_buton_prajituriActionPerformed

    private void buton_torturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_torturiActionPerformed
        // TODO add your handling code here:
        TorturiForm tort = new TorturiForm();
        tort.show();
        dispose();
    }//GEN-LAST:event_buton_torturiActionPerformed

    private void buton_ornamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ornamenteActionPerformed
        // TODO add your handling code here:
        OrnamenteForm orn = new OrnamenteForm();
        orn.show();
        dispose();
    }//GEN-LAST:event_buton_ornamenteActionPerformed

    private void buton_praj_japonezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_praj_japonezeActionPerformed
        // TODO add your handling code here:
        PrajituriJaponezeForm japan = new PrajituriJaponezeForm();
        japan.show();
        dispose();
    }//GEN-LAST:event_buton_praj_japonezeActionPerformed

    
    
    private int repetUrsi=0;
    private void buton_decor_ursuletiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_decor_ursuletiActionPerformed
        // TODO add your handling code here:
        repetUrsi++;
        if(repetUrsi == 1){
            this.cautareProd("Decor ursuleti 8buc/pachet", "ornamente");
            this.adaugareItem("Decor ursuleti 8buc/pachet", repetUrsi);
        }else{
            this.updateItem("Decor ursuleti 8buc/pachet", repetUrsi);
        }
    }//GEN-LAST:event_buton_decor_ursuletiActionPerformed

    private int repetPasta=0;
    private void buton_pasta_modelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_pasta_modelatActionPerformed
        // TODO add your handling code here:
        repetPasta++;
        if(repetPasta == 1){
            this.cautareProd("Pasta de modelat 1kg", "ornamente");
            this.adaugareItem("Pasta de modelat 1kg", repetPasta);
        }else{
            this.updateItem("Pasta de modelat 1kg", repetPasta);
        }
    }//GEN-LAST:event_buton_pasta_modelatActionPerformed

    private int repetPerle=0;
    private void buton_perle_ciocolata_albaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_perle_ciocolata_albaActionPerformed
        // TODO add your handling code here:
        repetPerle++;
        if(repetPerle == 1){
            this.cautareProd("Perle de ciocolata alba 1,2kg", "ornamente");
            this.adaugareItem("Perle de ciocolata alba 1,2kg", repetPerle);
        }else{
            this.updateItem("Perle de ciocolata alba 1,2kg", repetPerle);
        }
    }//GEN-LAST:event_buton_perle_ciocolata_albaActionPerformed

    private int repetFlori1=0;
    private void buton_decor_floriceleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_decor_floriceleActionPerformed
        // TODO add your handling code here:
        repetFlori1++;
        if(repetFlori1 == 1){
            this.cautareProd("Decor flori 12buc/pachet", "ornamente");
            this.adaugareItem("Decor flori 12buc/pachet", repetFlori1);
        }else{
            this.updateItem("Decor flori 12buc/pachet", repetFlori1);
        }
    }//GEN-LAST:event_buton_decor_floriceleActionPerformed

    private int repetTrand=0;
    private void buton_trandafiri_albi_perlatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_trandafiri_albi_perlatiActionPerformed
        // TODO add your handling code here:
        repetTrand++;
        if(repetTrand == 1){
            this.cautareProd("Decor Trandafir Alb Perlat 24buc", "ornamente");
            this.adaugareItem("Decor Trandafir Alb Perlat 24buc", repetTrand);
        }else{
            this.updateItem("Decor Trandafir Alb Perlat 24buc", repetTrand);
        }
    }//GEN-LAST:event_buton_trandafiri_albi_perlatiActionPerformed

    private int repetTrMod=0;
    private void buton_trandafiri_modelatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_trandafiri_modelatiActionPerformed
        // TODO add your handling code here:
        repetTrMod++;
        if(repetTrMod == 1){
            this.cautareProd("Trandafiri modelati 12buc/pachet", "ornamente");
            this.adaugareItem("Trandafiri modelati 12buc/pachet", repetTrMod);
        }else{
            this.updateItem("Trandafiri modelati 12buc/pachet", repetTrMod);
        }
    }//GEN-LAST:event_buton_trandafiri_modelatiActionPerformed

    private int repetPhoenix=0;
    private void buton_phoenixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_phoenixActionPerformed
        // TODO add your handling code here:
        repetPhoenix++;
        if(repetPhoenix == 1){
            this.cautareProd("Figurina Phoenix handmade", "ornamente");
            this.adaugareItem("Figurina Phoenix handmade", repetPhoenix);
        }else{
            this.updateItem("Figurina Phoenix handmade", repetPhoenix);
        }
        
    }//GEN-LAST:event_buton_phoenixActionPerformed

    private int figNunta=0;
    private void buton_figurina_nuntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_figurina_nuntaActionPerformed
        // TODO add your handling code here:
        figNunta++;
        if(figNunta == 1){
            this.cautareProd("Figurina Nunta", "ornamente");
            this.adaugareItem("Figurina Nunta", figNunta);
        }else{
            this.updateItem("Figurina Nunta", figNunta);
        }
    }//GEN-LAST:event_buton_figurina_nuntaActionPerformed

    private int repetFazani=0;
    private void buton_cuplu_fazaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_cuplu_fazaniActionPerformed
        // TODO add your handling code here:
        repetFazani++;
        if(repetFazani == 1){
            this.cautareProd("Figurina Cuplu Fazani", "ornamente");
            this.adaugareItem("Figurina Cuplu Fazani", repetFazani);
        }else{
            this.updateItem("Figurina Cuplu Fazani", repetFazani);
        }
    }//GEN-LAST:event_buton_cuplu_fazaniActionPerformed

    private void buton_cos_cumparaturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_cos_cumparaturiActionPerformed
        // TODO add your handling code here:
        CosCumparaturi cos =new CosCumparaturi();
        cos.show();
        dispose();
    }//GEN-LAST:event_buton_cos_cumparaturiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrnamenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrnamenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrnamenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrnamenteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrnamenteForm().setVisible(true);
            }
        });
        OrnamenteForm mp3 = new OrnamenteForm("C:\\Users\\User\\Desktop\\ChocolateriaPup\\src\\resurse\\fairytale.mp3");
        mp3.play();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buton_cos_cumparaturi;
    private java.awt.Button buton_cuplu_fazani;
    private java.awt.Button buton_decor_floricele;
    private java.awt.Button buton_decor_ursuleti;
    private java.awt.Button buton_figurina_nunta;
    private java.awt.Button buton_ornamente;
    private java.awt.Button buton_pasta_modelat;
    private java.awt.Button buton_perle_ciocolata_alba;
    private java.awt.Button buton_phoenix;
    private java.awt.Button buton_praj_japoneze;
    private java.awt.Button buton_prajituri;
    private java.awt.Button buton_torturi;
    private java.awt.Button buton_trandafiri_albi_perlati;
    private java.awt.Button buton_trandafiri_modelati;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
