/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocolateriapup;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import javazoom.jl.player.Player;

/**
 *
 * @author Isabella
 */
public class PrajituriForm extends javax.swing.JFrame {

    /**
     * Creates new form PrajituriForm
     */
    public PrajituriForm() {
        initComponents();
    }

    
    public String filename;
    public Player player; 


    public PrajituriForm(String filename) {
 this.filename = filename;
    }


    public void play() {
 try {   
            BufferedInputStream buffer = new BufferedInputStream(
    new FileInputStream(filename));
     player = new Player(buffer);
     player.play();
 }
 catch (Exception e) {

     System.out.println(e);
 }

    }
    public void stop(){
        try {   
            BufferedInputStream buffer = new BufferedInputStream(
    new FileInputStream(filename));
     player = new Player(buffer);
     player.close();
 }
 catch (Exception e) {

     System.out.println(e);
 }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buton_ornamente = new java.awt.Button();
        buton_torturi = new java.awt.Button();
        buton_cos_cumparaturi = new java.awt.Button();
        buton_prajituri = new java.awt.Button();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        buton_amandina = new java.awt.Button();
        label3 = new java.awt.Label();
        jLabel3 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        buton_boema = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        buton_ecler = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        buton_macarons = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        buton_tarta = new java.awt.Button();
        jLabel7 = new javax.swing.JLabel();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        buton_tiramisu = new java.awt.Button();
        buton_praj_japoneze = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/logo.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));

        buton_ornamente.setBackground(new java.awt.Color(255, 153, 153));
        buton_ornamente.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_ornamente.setLabel("Ornamente");
        buton_ornamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ornamenteActionPerformed(evt);
            }
        });

        buton_torturi.setBackground(new java.awt.Color(255, 153, 153));
        buton_torturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_torturi.setLabel("Torturi");
        buton_torturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_torturiActionPerformed(evt);
            }
        });

        buton_cos_cumparaturi.setBackground(new java.awt.Color(0, 204, 153));
        buton_cos_cumparaturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_cos_cumparaturi.setLabel("Cos de cumparaturi");
        buton_cos_cumparaturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_cos_cumparaturiActionPerformed(evt);
            }
        });

        buton_prajituri.setBackground(new java.awt.Color(255, 153, 153));
        buton_prajituri.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_prajituri.setLabel("Prajituri");
        buton_prajituri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_prajituriActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Amandina.jpg"))); // NOI18N

        label1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label1.setText("Amandina");

        label2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("10 RON / buc");

        buton_amandina.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_amandina.setLabel("Adauga");
        buton_amandina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_amandinaActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label3.setText("Boema");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Boema.jpg"))); // NOI18N

        label4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label4.setName(""); // NOI18N
        label4.setText("9,50 RON / buc");

        buton_boema.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_boema.setLabel("Adauga");
        buton_boema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_boemaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Ecler.jpg"))); // NOI18N

        label5.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label5.setText("Eclere");

        label6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("10 RON / buc");

        buton_ecler.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_ecler.setLabel("Adauga");
        buton_ecler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_eclerActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Macarons-Asortate.jpg"))); // NOI18N

        label7.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label7.setText("Macarons");

        label8.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label8.setName(""); // NOI18N
        label8.setText("5 RON / buc");

        buton_macarons.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_macarons.setLabel("Adauga");
        buton_macarons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_macaronsActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tarta-cu-Fructe.jpg"))); // NOI18N

        label9.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label9.setText("Tarta cu fructe");

        label10.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label10.setName(""); // NOI18N
        label10.setText("6,50 RON / buc");

        buton_tarta.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_tarta.setLabel("Adauga");
        buton_tarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_tartaActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tiramisu.jpg"))); // NOI18N

        label11.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label11.setText("Tiramisu");

        label12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label12.setName(""); // NOI18N
        label12.setText("8,50 RON / buc");

        buton_tiramisu.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_tiramisu.setLabel("Adauga");
        buton_tiramisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_tiramisuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buton_amandina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buton_boema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buton_ecler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buton_macarons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(202, 202, 202))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(buton_tarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_tiramisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_amandina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_boema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buton_ecler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_macarons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_tarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_tiramisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(658, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        buton_praj_japoneze.setBackground(new java.awt.Color(255, 153, 153));
        buton_praj_japoneze.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_praj_japoneze.setLabel("Prajituri japoneze");
        buton_praj_japoneze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_praj_japonezeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private String tip;
    private int produs_id, discount, repetare=0;
    private double pret;
    
    private void cautareProd(String denumire, String tip){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
//            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
//            stmt.executeUpdate(strUpdate);
            PreparedStatement search = con.prepareStatement("Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"' ");
            ResultSet rst = search.executeQuery();
            
            while(rst.next()){
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               produs_id = rst.getInt("id");
               discount = rst.getInt("discount");
               pret = rst.getDouble("pret");
            }
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }
    private void adaugareItem(String denumireProd, int repetari){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            String strUpdate = "INSERT INTO `cart_item` (`id`, `produs_id`, `denumire` ,`pret`, `discount`, `repetare`) "
                    + "VALUES (NULL, '"+produs_id+"', '"+denumireProd+"' ,'"+pret+"', '"+discount+"', '"+repetari+"');";
            stmt.executeUpdate(strUpdate);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }
    private double pretUpdate;
    private void updateItem(String denumire, int repetari){
        try{  
            
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            String strUpdate = "UPDATE `cart_item` SET `repetare` = '"+repetari+"' WHERE `cart_item`.`denumire` LIKE '"+denumire+"' ";
            stmt.executeUpdate(strUpdate);
            String strUpdatePret = "UPDATE `cart_item` set `pret` = '"+pret+"'*'"+repetari+"' WHERE `cart_item`.`denumire` LIKE '"+denumire+"' ";
            stmt.executeUpdate(strUpdatePret);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
        
    }
    
    
    
    private void buton_prajituriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_prajituriActionPerformed
        // TODO add your handling code here:
        PrajituriForm prajForm = new PrajituriForm();
        prajForm.show();
        dispose();
    }//GEN-LAST:event_buton_prajituriActionPerformed

    private void buton_torturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_torturiActionPerformed
        // TODO add your handling code here:
        TorturiForm tort = new TorturiForm();
        tort.show();
        dispose();
    }//GEN-LAST:event_buton_torturiActionPerformed

    private void buton_ornamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ornamenteActionPerformed
        // TODO add your handling code here:
        
         OrnamenteForm orn = new OrnamenteForm();
        orn.show();
        dispose();
    }//GEN-LAST:event_buton_ornamenteActionPerformed
        
    private void buton_praj_japonezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_praj_japonezeActionPerformed
        // TODO add your handling code here:
        PrajituriJaponezeForm japan = new PrajituriJaponezeForm();
        japan.show();
        dispose();
    }//GEN-LAST:event_buton_praj_japonezeActionPerformed
    
    
    private int repetareAman=0, repetareBoe=0, repetareEcler=0, repetareMac=0, repetareTart=0, repetareTiramis=0;
    
    private void buton_amandinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_amandinaActionPerformed
        // TODO add your handling code here:
        repetareAman++;
//        this.cautareProd("Amandina", "prajitura");
        if(repetareAman == 1){
            this.cautareProd("Amandina", "prajitura");
            this.adaugareItem("Amandina", repetareAman);
        }else{
            this.updateItem("Amandina", repetareAman);
        }
        
    }//GEN-LAST:event_buton_amandinaActionPerformed

    private void buton_cos_cumparaturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_cos_cumparaturiActionPerformed
        // TODO add your handling code here:
        
        CosCumparaturi cos = new CosCumparaturi();
//        PrajituriForm mp3 = new PrajituriForm("C:\\Users\\Isabella\\Documents\\NetBeansProjects\\ChocolateriaPup\\src\\resurse\\try.mp3");
//        mp3.stop();
//        CosCumparaturi mp3Cos = new CosCumparaturi("C:\\Users\\Isabella\\Documents\\NetBeansProjects\\ChocolateriaPup\\src\\resurse\\try2.mp3");
//        mp3Cos.play();
//        player.close();
        cos.show();
        dispose();
    }//GEN-LAST:event_buton_cos_cumparaturiActionPerformed

    private void buton_boemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_boemaActionPerformed
        // TODO add your handling code here:
        repetareBoe++;
        if(repetareBoe == 1){
            this.cautareProd("Boema", "prajitura");
            this.adaugareItem("Boema", repetareBoe);
            
        }else{
            this.updateItem("Boema", repetareBoe);
        }
        
    }//GEN-LAST:event_buton_boemaActionPerformed

    private void buton_eclerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_eclerActionPerformed
        // TODO add your handling code here:
        repetareEcler++;
        if(repetareEcler == 1){
            this.cautareProd("Ecler", "prajitura");
            this.adaugareItem("Ecler", repetareEcler);
        }else{
            this.updateItem("Ecler", repetareEcler);
        }
        
    }//GEN-LAST:event_buton_eclerActionPerformed

    private void buton_macaronsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_macaronsActionPerformed
        // TODO add your handling code here:
        repetareMac++;
        if(repetareMac == 1){
            this.cautareProd("Macarons", "prajitura");
            this.adaugareItem("Macarons", repetareMac);
        }else{
            this.updateItem("Macarons", repetareMac);
        }
    }//GEN-LAST:event_buton_macaronsActionPerformed

    private void buton_tartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_tartaActionPerformed
        // TODO add your handling code here:
        repetareTart++;
        if(repetareTart == 1){
            this.cautareProd("Tarta cu fructe", "prajitura");
            this.adaugareItem("Tarta cu fructe", repetareTart);
        }else{
            this.updateItem("Tarta cu fructe", repetareTart);
        }
    }//GEN-LAST:event_buton_tartaActionPerformed

    private void buton_tiramisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_tiramisuActionPerformed
        // TODO add your handling code here:
        repetareTiramis++;
        if(repetareTiramis == 1){
            this.cautareProd("Tiramisu", "prajitura");
            this.adaugareItem("Tiramisu", repetareTiramis);
        }else{
            this.updateItem("Tiramisu", repetareTiramis);
        }
    }//GEN-LAST:event_buton_tiramisuActionPerformed
    
    
    
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrajituriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrajituriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrajituriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrajituriForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrajituriForm().setVisible(true);
            }
        });
        PrajituriForm mp3 = new PrajituriForm("C:\\Users\\User\\Desktop\\ChocolateriaPup\\src\\resurse\\try.mp3");
        mp3.play();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buton_amandina;
    private java.awt.Button buton_boema;
    private java.awt.Button buton_cos_cumparaturi;
    private java.awt.Button buton_ecler;
    private java.awt.Button buton_macarons;
    private java.awt.Button buton_ornamente;
    private java.awt.Button buton_praj_japoneze;
    private java.awt.Button buton_prajituri;
    private java.awt.Button buton_tarta;
    private java.awt.Button buton_tiramisu;
    private java.awt.Button buton_torturi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
