/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chocolateriapup;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javazoom.jl.player.Player;

/**
 *
 * @author Isabella
 */
public class TorturiForm extends javax.swing.JFrame {

    /**
     * Creates new form TorturiForm
     */
    public TorturiForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buton_ornamente = new java.awt.Button();
        buton_torturi = new java.awt.Button();
        buton_cos_cumparaturi = new java.awt.Button();
        buton_prajituri = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        buton_cheesecake_buc = new java.awt.Button();
        label3 = new java.awt.Label();
        buton_cheesecake_kg = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        buton_fructe_padure_kg = new java.awt.Button();
        jLabel4 = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        buton_diplomat_kg = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        buton_ciocolata_alba_kg = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        buton_jamaica_kg = new java.awt.Button();
        buton_duo_kg = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        buton_mousse_kg = new java.awt.Button();
        buton_trio_mousse_kg = new java.awt.Button();
        buton_trio_mousse_buc = new java.awt.Button();
        label18 = new java.awt.Label();
        buton_praj_japoneze = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/logo.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));

        buton_ornamente.setBackground(new java.awt.Color(255, 153, 153));
        buton_ornamente.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_ornamente.setLabel("Ornamente");
        buton_ornamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ornamenteActionPerformed(evt);
            }
        });

        buton_torturi.setBackground(new java.awt.Color(255, 153, 153));
        buton_torturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_torturi.setLabel("Torturi");
        buton_torturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_torturiActionPerformed(evt);
            }
        });

        buton_cos_cumparaturi.setBackground(new java.awt.Color(0, 204, 153));
        buton_cos_cumparaturi.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_cos_cumparaturi.setLabel("Cos de cumparaturi");
        buton_cos_cumparaturi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_cos_cumparaturiActionPerformed(evt);
            }
        });

        buton_prajituri.setBackground(new java.awt.Color(255, 153, 153));
        buton_prajituri.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_prajituri.setLabel("Prajituri");
        buton_prajituri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_prajituriActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Cheesecake.jpg"))); // NOI18N

        label1.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label1.setText("Cheesecake");

        label2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("14 RON / buc ");

        buton_cheesecake_buc.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_cheesecake_buc.setLabel("Adauga buc.");
        buton_cheesecake_buc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_cheesecake_bucActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label3.setName(""); // NOI18N
        label3.setText("95 RON / KG");

        buton_cheesecake_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_cheesecake_kg.setLabel("Adauga");
        buton_cheesecake_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_cheesecake_kgActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Alina_1000x1000.jpg"))); // NOI18N

        label4.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label4.setText("Tort Fructe de Padure");

        label5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label5.setName(""); // NOI18N
        label5.setText("85 RON / KG");

        buton_fructe_padure_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_fructe_padure_kg.setLabel("Adauga");
        buton_fructe_padure_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_fructe_padure_kgActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Diplomat_1_1000x1000.jpg"))); // NOI18N

        label6.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label6.setText("Tort Diplomat");

        label7.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label7.setName(""); // NOI18N
        label7.setText("85 RON / KG");

        buton_diplomat_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_diplomat_kg.setLabel("Adauga");
        buton_diplomat_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_diplomat_kgActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Emoke_1000x1000.jpg"))); // NOI18N

        label8.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label8.setText("Tort Ciocolata Alba");

        label9.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label9.setName(""); // NOI18N
        label9.setText("110 RON / KG");

        buton_ciocolata_alba_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_ciocolata_alba_kg.setLabel("Adauga");
        buton_ciocolata_alba_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_ciocolata_alba_kgActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Jamaica_1000x1000.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Madrid_1000x1000.jpg"))); // NOI18N

        label10.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label10.setText("Tort Jamaica");

        label11.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label11.setText("Tort Duo");

        label12.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label12.setName(""); // NOI18N
        label12.setText("110 RON / KG");

        label13.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label13.setName(""); // NOI18N
        label13.setText("95 RON / KG");

        buton_jamaica_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_jamaica_kg.setLabel("Adauga");
        buton_jamaica_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_jamaica_kgActionPerformed(evt);
            }
        });

        buton_duo_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_duo_kg.setLabel("Adauga");
        buton_duo_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_duo_kgActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Mousse-de-Ciocolata-cu-Fructe-de-Padure_1000x1000.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resurse/Tort-Trio-Mousse_3_1000x1000.jpg"))); // NOI18N

        label14.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label14.setText("Tort Mousse");

        label15.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        label15.setText("Tort Trio Mousse");

        label16.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label16.setName(""); // NOI18N
        label16.setText("110 RON / KG");

        label17.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label17.setName(""); // NOI18N
        label17.setText("110 RON / KG");

        buton_mousse_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_mousse_kg.setLabel("Adauga");
        buton_mousse_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_mousse_kgActionPerformed(evt);
            }
        });

        buton_trio_mousse_kg.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_trio_mousse_kg.setLabel("Adauga");
        buton_trio_mousse_kg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_trio_mousse_kgActionPerformed(evt);
            }
        });

        buton_trio_mousse_buc.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        buton_trio_mousse_buc.setLabel("Adauga buc.");
        buton_trio_mousse_buc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_trio_mousse_bucActionPerformed(evt);
            }
        });

        label18.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        label18.setName(""); // NOI18N
        label18.setText("11 RON / buc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buton_diplomat_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buton_ciocolata_alba_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buton_jamaica_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(buton_duo_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(181, 181, 181))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(171, 171, 171)))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buton_cheesecake_buc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(buton_cheesecake_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(buton_mousse_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buton_trio_mousse_buc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(buton_trio_mousse_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(116, 116, 116))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(173, 173, 173))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(buton_fructe_padure_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(185, 185, 185))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(75, 75, 75)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_cheesecake_buc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_cheesecake_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_fructe_padure_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_diplomat_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_ciocolata_alba_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_jamaica_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_duo_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buton_mousse_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buton_trio_mousse_kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_trio_mousse_buc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane2.setViewportView(jScrollPane1);

        buton_praj_japoneze.setBackground(new java.awt.Color(255, 153, 153));
        buton_praj_japoneze.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        buton_praj_japoneze.setLabel("Prajituri japoneze");
        buton_praj_japoneze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_praj_japonezeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buton_prajituri, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_torturi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buton_ornamente, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(buton_praj_japoneze, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(buton_cos_cumparaturi, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private int produs_id, discount, repetare=0;
    private double pret;
    
    private void cautareProd(String denumire, String tip){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            //SELECT * FROM conturi WHERE username LIKE '"+username+"' AND password LIKE '"+password+"'
//            String strUpdate = "Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"'";
//            stmt.executeUpdate(strUpdate);
            PreparedStatement search = con.prepareStatement("Select * from produse where denumire LIKE '"+denumire+"' AND tip LIKE '"+tip+"' ");
            ResultSet rst = search.executeQuery();
            
            while(rst.next()){
//                 String to= rst.getString("Adresa Mail");
//                String parolaSQL = rst.getString("password");
               produs_id = rst.getInt("id");
               discount = rst.getInt("discount");
               pret = rst.getDouble("pret");
            }
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }
    private void adaugareItem(String denumireProd, int repetari){
        try{  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            String strUpdate = "INSERT INTO `cart_item` (`id`, `produs_id`, `denumire` ,`pret`, `discount`, `repetare`) "
                    + "VALUES (NULL, '"+produs_id+"', '"+denumireProd+"' ,'"+pret+"', '"+discount+"', '"+repetari+"');";
            stmt.executeUpdate(strUpdate);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
    }
    private double pretUpdate;
    private void updateItem(String denumire, int repetari){
        try{  
            
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/appslabit?characterEncoding=utf8","root","root");  
            Statement stmt=con.createStatement();
            String strUpdate = "UPDATE `cart_item` SET `repetare` = '"+repetari+"' WHERE `cart_item`.`denumire` LIKE '"+denumire+"' ";
            stmt.executeUpdate(strUpdate);
            String strUpdatePret = "UPDATE `cart_item` set `pret` = '"+pret+"'*'"+repetari+"' WHERE `cart_item`.`denumire` LIKE '"+denumire+"' ";
            stmt.executeUpdate(strUpdatePret);
            con.close();
            
//            this.sendMail(to);
        }catch(Exception e){ System.out.println(e);}
        
    }
    
    private int repetariChBuc=0, repetTrioMousseBuc=0, repetCheeseKg=0, repetFructePad =0;
    
    
    
    public String filename;
    public Player player; 


    public TorturiForm(String filename) {
 this.filename = filename;
    }


    public void play() {
 try {   
            BufferedInputStream buffer = new BufferedInputStream(
    new FileInputStream(filename));
     player = new Player(buffer);
     player.play();
 }
 catch (Exception e) {

     System.out.println(e);
 }
    }
    
    private void buton_ornamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ornamenteActionPerformed
        // TODO add your handling code here:
         OrnamenteForm orn = new OrnamenteForm();
        orn.show();
        dispose();
    }//GEN-LAST:event_buton_ornamenteActionPerformed

    private void buton_torturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_torturiActionPerformed
        // TODO add your handling code here:
        TorturiForm tort = new TorturiForm();
        tort.show();
        dispose();
    }//GEN-LAST:event_buton_torturiActionPerformed

    private void buton_prajituriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_prajituriActionPerformed
        // TODO add your handling code here:
        PrajituriForm prajForm = new PrajituriForm();
        prajForm.show();
        dispose();
    }//GEN-LAST:event_buton_prajituriActionPerformed

    private void buton_praj_japonezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_praj_japonezeActionPerformed
        // TODO add your handling code here:
        PrajituriJaponezeForm japan = new PrajituriJaponezeForm();
        japan.show();
        dispose();
    }//GEN-LAST:event_buton_praj_japonezeActionPerformed

    private void buton_cheesecake_bucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_cheesecake_bucActionPerformed
        // TODO add your handling code here:
        
        repetariChBuc++;
        if(repetariChBuc == 1){
            this.cautareProd("Cheesecake buc.", "prajitura");
            this.adaugareItem("Cheesecake buc.", repetariChBuc);
        }else{
            this.updateItem("Cheesecake buc.", repetariChBuc);
        }
    }//GEN-LAST:event_buton_cheesecake_bucActionPerformed

    private void buton_trio_mousse_bucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_trio_mousse_bucActionPerformed
        // TODO add your handling code here:
        
        
        repetTrioMousseBuc++;
        if(repetTrioMousseBuc == 1){
            this.cautareProd("Tort Trio Mousse buc.", "prajitura");
            this.adaugareItem("Tort Trio Mousse buc.", repetTrioMousseBuc);
        }else{
            this.updateItem("Tort Trio Mousse buc.", repetTrioMousseBuc);
        }
        
    }//GEN-LAST:event_buton_trio_mousse_bucActionPerformed

    private void buton_cheesecake_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_cheesecake_kgActionPerformed
        // TODO add your handling code here:
         
        
        repetCheeseKg++;
        if(repetCheeseKg == 1){
            this.cautareProd("Cheesecake Tort", "tort");
            this.adaugareItem("Cheesecake Tort", repetCheeseKg);
        }else{
            this.updateItem("Cheesecake Tort", repetCheeseKg);
        }
    }//GEN-LAST:event_buton_cheesecake_kgActionPerformed

    private void buton_fructe_padure_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_fructe_padure_kgActionPerformed
        // TODO add your handling code here:
        repetFructePad++;
        if(repetFructePad == 1){
            this.cautareProd("Tort fructe de padure", "tort");
            this.adaugareItem("Tort fructe de padure", repetFructePad);
        }else{
            this.updateItem("Tort fructe de padure", repetFructePad);
        }
    }//GEN-LAST:event_buton_fructe_padure_kgActionPerformed
    
    private int repetDipl=0;
    private void buton_diplomat_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_diplomat_kgActionPerformed
        // TODO add your handling code here:
        repetDipl++;
        if(repetDipl == 1){
            this.cautareProd("Tort diplomat", "tort");
            this.adaugareItem("Tort diplomat", repetDipl);
        }else{
            this.updateItem("Tort diplomat", repetDipl);
        }
    }//GEN-LAST:event_buton_diplomat_kgActionPerformed

    private int repetCiocTort=0;
    private void buton_ciocolata_alba_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_ciocolata_alba_kgActionPerformed
        // TODO add your handling code here:
        repetCiocTort++;
        if(repetCiocTort == 1){
            this.cautareProd("Tort ciocolata alba", "tort");
            this.adaugareItem("Tort ciocolata alba", repetCiocTort);
        }else{
            this.updateItem("Tort ciocolata alba", repetCiocTort);
        }
    }//GEN-LAST:event_buton_ciocolata_alba_kgActionPerformed

    private int repetJamai=0;
    private void buton_jamaica_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_jamaica_kgActionPerformed
        // TODO add your handling code here:
        repetJamai++;
        if(repetJamai == 1){
            this.cautareProd("Tort jamaica", "tort");
            this.adaugareItem("Tort jamaica", repetJamai);
        }else{
            this.updateItem("Tort jamaica", repetJamai);
        }
    }//GEN-LAST:event_buton_jamaica_kgActionPerformed

    private int repetDuo=0;
    private void buton_duo_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_duo_kgActionPerformed
        // TODO add your handling code here:
        repetDuo++;
        if(repetDuo == 1){
            this.cautareProd("Tort Duo", "tort");
            this.adaugareItem("Tort Duo", repetDuo);
        }else{
            this.updateItem("Tort Duo", repetDuo);
        }
    }//GEN-LAST:event_buton_duo_kgActionPerformed

    private int repetMousse=0;
    private void buton_mousse_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_mousse_kgActionPerformed
        // TODO add your handling code here:
        repetMousse++;
        if(repetMousse == 1){
            this.cautareProd("Tort Mousse", "tort");
            this.adaugareItem("Tort Mousse", repetMousse);
        }else{
            this.updateItem("Tort Mousse", repetMousse);
        }
    }//GEN-LAST:event_buton_mousse_kgActionPerformed

    private int repetTrioKg=0;
    private void buton_trio_mousse_kgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_trio_mousse_kgActionPerformed
        // TODO add your handling code here:
        repetTrioKg++;
        if(repetTrioKg == 1){
            this.cautareProd("Tort Trio Mousse kg.", "tort");
            this.adaugareItem("Tort Trio Mousse kg.", repetTrioKg);
        }else{
            this.updateItem("Tort Trio Mousse kg.", repetTrioKg);
        }
    }//GEN-LAST:event_buton_trio_mousse_kgActionPerformed

    private void buton_cos_cumparaturiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_cos_cumparaturiActionPerformed
        // TODO add your handling code here:
        CosCumparaturi cos = new CosCumparaturi();
        cos.show();
        dispose();
    }//GEN-LAST:event_buton_cos_cumparaturiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TorturiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TorturiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TorturiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TorturiForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TorturiForm().setVisible(true);
            }
        });
        TorturiForm tort = new TorturiForm("C:\\Users\\User\\Desktop\\ChocolateriaPup\\src\\resurse\\twoOfUs.mp3");
        tort.play();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buton_cheesecake_buc;
    private java.awt.Button buton_cheesecake_kg;
    private java.awt.Button buton_ciocolata_alba_kg;
    private java.awt.Button buton_cos_cumparaturi;
    private java.awt.Button buton_diplomat_kg;
    private java.awt.Button buton_duo_kg;
    private java.awt.Button buton_fructe_padure_kg;
    private java.awt.Button buton_jamaica_kg;
    private java.awt.Button buton_mousse_kg;
    private java.awt.Button buton_ornamente;
    private java.awt.Button buton_praj_japoneze;
    private java.awt.Button buton_prajituri;
    private java.awt.Button buton_torturi;
    private java.awt.Button buton_trio_mousse_buc;
    private java.awt.Button buton_trio_mousse_kg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
